import React, { Component } from 'react'

class AddPost extends Component {
  state = {
    title: '',
    body: '',
    id: null
    //todo autogenerate id
  }

  onSubmit = e => {
    e.preventDefault();
    console.log(this.state)
  }

  onChange = e => this.setState({
    [e.target.name]: e.target.value
})
  render() {
    const { title, body, id } = this.state;
    return (
      <div className="card mb-2">
        <div className="card-header">Add post</div>
        <div className="card-body">
          <form>
            <div className="form-group">
              <label htmlFor="title">Title</label>
              <input 
                type="text" 
                name="title"
                className="form-control form-control-sm"
                placeholder="Insert title"
                value={title}
                onChange={this.on}
                onChange={this.onChange}
              />
            </div>
            <div className="form-group">
              <label htmlFor="body">Body</label>
              <textarea 
                type="textarea" 
                name="body"
                className="form-control form-control-sm"
                placeholder="Insert title"
                value={body}
                onChange={this.onChange}
              />
            </div>
           <p>id autogenerated: {id}</p>
           <input type="submit" value="Add post" className="btn btn-sm btn-block btn-outline-success" onClick={this.onSubmit}/>
          </form>
        </div>
      </div>
    )
  }
}

export default AddPost;
